# Generated by Django 5.0.7 on 2024-08-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('r_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('created_at', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('publish', 'publish'), ('not publish', 'not publish')], max_length=50)),
                ('genres', models.CharField(choices=[('action', 'action'), ('thriller', 'thriller'), ('horror', 'horror'), ('sci-fi', 'sci-fi'), ('comedy', 'comedy')], max_length=50)),
            ],
        ),
    ]
